# ¿Cómo utilizar estos datos?

Para cargar estos datos hay que descargar y descomprimir en tu ordenador el fichero que contiene cada banco de datos. Una vez descargado se proporciona la sentencia para su carga. Se proporciona además un fichero pdf que contiene la descripción completa de todos los bancos de datos. 

# Bancos de datos

Nombre             | Descripción
-------------------|------------------------------------------------------------
BOD2       |   The BOD2 data frame has 8 rows and 2 columns giving the biochemical oxygen demand versus time in an evaluation of water quality.
Chloride|The Chloride data frame has 54 rows and 2 columns representing measurements of the chloride ion concentration in blood cells suspended in a salt solution.
Coal|The Coal data frame has 23 rows and 20 columns of data on a coal liquefaction process.
Ethyl|The Ethyl data frame has 12 rows and 3 columns of ethyl acrylate concentrations in exhalate of a rat.

# Carga de un ejemplo
```{r BOD2, eval=FALSE}
# Seleccionas el fichero BOD2.rda y lo descargamos en tu directorio de trabajo. Abrimos la sesión de trabajo y ejcecutamos las sentencias siguientes
library(tidyverse)
load("BOD2.rda")
attach(BOD2)
```

# Referencias
>Bates and Watts (1998), Nonlinear Regression Analysis and Its Applications, Wiley,
