# ¿Cómo utilizar estos datos?

Para cargar estos datos hay que descargar y descomprimir en tu ordenador el fichero que contiene cada banco de datos. Una vez descargado se proporciona la sentencia para su carga. Se proporciona además un fichero pdf que contiene la descripción completa de todos los bancos de datos. 

# Bancos de datos

Nombre             | Descripción
-------------------|------------------------------------------------------------
BOD2       |   The BOD2 data frame has 8 rows and 2 columns giving the biochemical oxygen demand versus time in an evaluation of water quality.
Chloride|The Chloride data frame has 54 rows and 2 columns representing measurements of the chloride ion concentration in blood cells suspended in a salt solution.
Coal|The Coal data frame has 23 rows and 20 columns of data on a coal liquefaction process.
Ethyl|The Ethyl data frame has 12 rows and 3 columns of ethyl acrylate concentrations in exhalate of a rat.
Isom|The Isom data frame has 24 rows and 4 columns from an isomerization experiment.
Leaves|The Leaves data frame has 15 rows and 2 columns of leaf length over time.
Lipo|The Lipo data frame has 12 rows and 2 columns of lipoprotein concentrations over time.
Lubricant|The Lubricant data frame has 53 rows and 3 columns on the viscosity of a lubricant at different pressures and temperatures.
Nitren|The Nitren data frame has 26 rows and 5 columns from an experiment in cardiology.
Nitrite|The Nitrite data frame has 48 rows and 3 columns giving nitrite utilization by bean leaves under different light conditions on two different days.
O.xylene|The O.xylene data frame has 57 rows and 4 columns of data on a chemical engineering experiment.
Oilshale|The Oilshale data frame has 64 rows and 4 columns from an experiment on the pyrolysis of oil shale.
PCB|The PCB data frame has 28 rows and 2 columns giving the concentration of polychlorinated biphenyls (PCB’s) in fish caught in Lake Cayuga in northern New York state. The fish had been tagged as yearlings so their ages could be accurately determined.
Pinene|The Pinene data frame has 8 rows and 6 columns giving the proportion of alpha-pinene and four of its by-products over time.
Pinene2|The Pinene data frame has 8 rows and 6 columns giving the proportion of alpha-pinene and four of its by-products over time from a second experiment.
Rumford|The Rumford data frame has 13 rows and 2 columns from an experiment by Count Rumford on the rate of cooling.
Sacch2|The Sacch2 data frame has 10 rows and 2 columns from an experiment on the pharmacokinetics of saccharin.
Saccharin|The Saccharin data frame has 9 rows and 3 columns from an experiment on the elimination of saccharin.
sPMMA|The sPMMA data frame has 23 rows and 3 columns from an experiment on the dielectric response of a sample of syndiotactic poly-methyl-methacrylate (sPMMA).
Sulfi|The Sulfi data frame has 12 rows and 2 columns from an experiment on the pharmacokinetics of sulfisoxazole.
Tetra|The Tetra data frame has 9 rows and 2 columns from an experiment on the pharmacokinetics of tetracycline.



# Carga de un ejemplo
```{r BOD2, eval=FALSE}
# Seleccionas el fichero BOD2.rda y lo descargamos en tu directorio de trabajo. Abrimos la sesión de trabajo y ejcecutamos las sentencias siguientes
library(tidyverse)
load("BOD2.rda")
attach(BOD2)
```

# Referencias
>Bates and Watts (1998), Nonlinear Regression Analysis and Its Applications, Wiley,
