# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
ml_reg_01.csv       |   The data show responses, percentages of total calories obtained from complex carbohydrates, for twenty male insulin-dependent diabetics who had been on a high-carbohydrate diet for six months. Compliance with the regime was thought to be related to age (in years), body weight (relative to ‘ideal’ weight for height) and other components of the diet, such as the percentage ofcalories as protein (Table 6.3 Dobson).
ml_reg_02.csv       |   An experiment was conducted to compare yields (measured by dried weight of plants) under a control condition and two different treatment conditions. (Table 6.6 Dobson).
ml_reg_03.csv       |   Data shows the average apparent per capita consumption ofsuga r (in kg per year) in Australia, as refined sugar and in manufactured foods (from Australian Bureau ofStatistics, 1998). (Table 6.15 Dobson).
ml_reg_04.csv       |  Table shows response of a grass and legume pasture system to various quantities of phosphorus fertilizer (data from D. F. Sinclair; the results were reported in Sinclair and Probert, 1986). The total yield, ofgrass and legume together, and amount ofphosphorus (K) are both given in kilograms per hectare. (Table 6.16 Dobson).
ml_reg_05.csv       |  It is well known that the concentration of cholesterol in blood serum increases with age but it is less clear whether cholesterol level is also associated with body weight. Data shows for thirty women serumcholesterol (millimoles per liter), age (years) and body mass index (weight divided by height squared, where weight was measured in kilograms and height in meters). (Table 6.17 Dobson).

# Ejecución para la lectura de cada fichero

```{r ml, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(forcats)
##### Lectura de cada ejemplo
# ml_reg_01
ml_reg_01=read_csv("https://goo.gl/Grm8xM", col_types = "dddd")
str(ml_reg_01)
# ml_reg_02
ml_reg_02=read_csv("https://goo.gl/gRThLb", col_types = "cd")
str(ml_reg_02)
# ml_reg_03
ml_reg_03=read_csv("https://goo.gl/w5KzKh", col_types = "cdd")
str(ml_reg_03)
# ml_reg_04
ml_reg_04=read_csv("https://goo.gl/AOikQU", col_types = "dd")
str(ml_reg_04)
# ml_reg_05
ml_reg_05=read_csv("https://goo.gl/EKXWRc", col_types = "ddd")
str(ml_reg_05)
```
# Bibliografía

>Dobson (2002). An introduction to generalized linear models
