A continuación se presentan los bancos de datos básicos que utilizaremos en la primera parte del curso y como ejemplo de algunos de los modelos que veremos en la segunda parte.


# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
airquality      |Daily readings of the following air quality values for May 1, 1973 (a Tuesday) to September 30, 1973. 
esoph      |Data from a case-control study of (o)esophageal cancer in Ille-et-Vilaine, France. 
mpg      |This dataset contains a subset of the fuel economy data that the EPA makes available on http://fueleconomy.gov. It contains only models which had a new release every year between 1999 and 2008 - this was used as a proxy for the popularity of the car. Variables in data set: manufacturer model (model name); displ (engine displacement, in litres); year (year of manufacture); cyl (number of cylinders); trans (type of transmission); drv (f = front-wheel drive, r = rear wheel drive, 4 = 4wd); cty (city miles per gallon); hwy (highway miles per gallon); fl (fuel type); class ("type" of car).
Puromycin      |The Puromycin data frame has 23 rows and 3 columns of the reaction velocity versus substrate concentration in an enzymatic reaction involving untreated cells or cells treated with Puromycin.
NCBIRTH800      |The table presents data from birth and infant death data for all children born in the state of North Carolina. This comprenhensive data set for the births in 2001. The variables are as follows: plural (number of children born of the pregnancy),	sex (sex of child),	mage (age of mother),	weeks (completed weeks of gestation),	marital (marital status),	racemom (race of mother),	hispmom (mother of hispanic origin),	gained (weight gained during pregnancy in pounds), smoke,	drink, tounces (weight of child in onces),	tgrams (weight of child in grams), low (low birth weight),	premie (premature) (pag 56, Daniel)
CHOLEST      | Data refer to the serum cholesterol levels for 1000 subjects(pag 206, Daniel)
HEADCIR      | Data refer to the head circumference of 1000 matched subjects(pag 297, Daniel)
PCKDATA      | Data refer to the creatine phosphokinase (two groups of subjects) (pag 297, Daniel)
LSADATA | Data refer to the serum lipid-bound sialic data. We wish to conduct a study to determine if the measurements of serum might be of use in the detection of breast cancer. The measurements are for four populations of subjects: A (Control), B (patients with benign breast disease), C (patients with primary breast cancer), D (patients with recurrent metastasic breast cancer) (pag 403, Daniel)
SACEDATA| Data refer to the serum angiotensin-converting enzyme (SACE). Sarcoidosis is a systemic ganulomatous disease of unknown cause. The assay SACE is hepful in the diagnosis of active sarcoidosis. The activity of SACE is usually increased with patients with the disease. The data are the SACE values for four populations of subjects according to the status regarding sarcoidosis: A (never had), B (active), C (stable), D (recovered) (pag 403, Daniel)
SERUMCHO| Data refer to the serum cholesterol (chol).  Adult males between the ages of 30 and 65 participed in a study to investigate the relationship between the consumption of meat and serum cholesterol. The data are de chol values for three populations of subjects according after a diet of 20 weeks: BEEF (only meat beef), PORK (only meat pork), CHFISH (only meat chicken and fish) (pag 404, Daniel)

# Ejecución para la lectura de cada fichero

```{r ml, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(stringr)
library(forcats)
library(lubridate)
library(magrittr)
library(broom)
library(datasets)

##### Bancos de datos de la libreria datasets

# airquality
attach(airquality)
help(airquality)
str(airquality)

# esoph
attach(esoph)
help(esoph)
str(esoph)

# mtcars
data(mmp)
help(mpg)
str(mpg)

# Puromycin
attach(Puromycin)
help(Puromycin)
str(Puromycin)

##### Bancos de datos del libro de Daniel: Biostatistics

# NCBIRTH800
NCBIRTH800=read_csv("https://goo.gl/mB9Jcn", col_types = "dcddcccdccddcc")
str(NCBIRTH800)
# Recodificación del factor
NCBIRTH800 %>% mutate(sex=fct_recode(sex,"male"="1","female"="2"),marital=fct_recode(marital,"married"="1","not married"="2"),racemom=fct_recode(racemom,"other non white"="0","White"="1","Black"="2","America indian"="3","Chinese"="4","Hawaiian"="5","Filipino"="6","Other asian"="7"),hispmom=fct_recode(hispmom,"Cuban"="C","Mexican"="M","Non-Hispanic"="N","Other"="O","Puerto Rican"="P","Central/South american"="S","U"="Not classificable"),smoke=fct_recode(smoke,"Yes"="1","No"="0"),drink=fct_recode(drink,"Yes"="1","No"="0"),low=fct_recode(low,"Yes"="1","No"="0"),premie=fct_recode(premie,"Yes"="1","No"="0"))

# CHOLEST
CHOLEST=read_csv("https://goo.gl/b5ZAb1", col_types = "id")
str(CHOLEST)

# HEADCIR
HEADCIR=read_csv("https://goo.gl/juWJEu", col_types = "idd")
str(HEADCIR)

# PCKDATA 
PCKDATA =read_csv("https://goo.gl/W8Bfgv", col_types = "idd")
str(PCKDATA)
# Construimos la tabla donde cada fila recoje a un sujeto de cada tratamiento
PCKDATAb = PCKDATA %>% gather(`A`,`B`, key = "Grupo", value = creatine)

# LSADATA 
LSADATA =read_csv("https://goo.gl/m7ewG9", col_types = "idddd")
str(LSADATA)
# Construimos la tabla donde cada fila recoje a un sujeto de cada tratamiento
LSADATAb = LSADATA %>% gather(`A`,`B`, `C`,`D`,key = "Grupo", value = lsa)

# LSADATA 
SACEDATA =read_csv("https://goo.gl/FwMcTu", col_types = "idddd")
str(SACEDATA)
# Construimos la tabla donde cada fila recoje a un sujeto de cada tratamiento
SACEDATAb = SACEDATA %>% gather(`A`,`B`, `C`,`D`,key = "Grupo", value = sace)

# SERUMCHO 
SERUMCHO =read_csv("https://goo.gl/ghxka2", col_types = "iddd")
str(SERUMCHO)
# Construimos la tabla donde cada fila recoje a un sujeto de cada tratamiento
SERUMCHOb = SERUMCHO %>% gather(`BEEF`,`PORK`, `CHFISH`,key = "Dieta", value = chol)
```
