# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
glm_multi_01.csv       |   In a study ofmotor vehicle safety, men and women driving small, medium sized and large cars were interviewed about vehicle safety and their preferences for cars, and various measurements were made of how close they sat to the steering wheel (McFadden et al., 2000). They were asked to rate how important various features were to them when they were buying a car. Data table shows the ratings for air conditioning and power steering, according to the sex and age ofthe subject (the categories ‘not important’ and ‘of little importance’ have been combined). (Table 8.1 Dobson).
glm_multi_02.csv       |   The data are from an investigation into satisfaction with housing conditions in Copenhagen (derived from Example W in Cox and Snell, 1981, from original data from Madsen, 1971). Residents in selected areas living in rented homes built between 1960 and 1968 were questioned about their satisfaction and the degree of contact with other residents. The data were tabulated by type ofhousing. (Table 8.5 Dobson).
glm_multi_03.csv       |   The data show tumor responses of male and female patients receiving treatment for small-cell lung cancer. There were two treatment regimes. For the sequential treatment, the same combination ofc hemotherapeutic agents was administered at each treatment cycle. For the alternating treatment, different combinations were alternated from cycle to cycle (data from Holtbrugger and Schumacher, 1991). (Table 8.6 Dobson).
glm_multi_04.csv       |   The data are from a famous study conducted by Sir Richard Doll and colleagues. In 1951, all British doctors were sent a brief questionnaire about whether they smoked tobacco. Since then information about their deaths has been collected. Table shows the numbers ofdeath s from coronary heart disease among male doctors 10 years after the survey. It also shows the total number ofp erson-years ofobserv ation at the time ofthe analysis (Breslow and Day, 1987: Appendix 1A and page 112). (Table 9.1 Dobson).
glm_multi_05.csv       |   These data are from a cross-sectional study of patients with a form of skin cancer called malignant melanoma. For a sample of n = 400 patients, the site ofthe tumor and its histological type were recorded. (Table 9.4 Dobson).
glm_multi_06.csv       |   In a prospective study ofa new living attenuated recombinant vaccine for influenza, patients were randomly allocated to two groups, one of whic h was given the new vaccine and the other a saline placebo. The responses were titre levels of hemagglutinin inhibiting antibody found in the blood six weeks after vaccination; they were categorized as ‘small’, ‘medium’ or ‘large’.(Table 9.6 Dobson).
glm_multi_07.csv       |  In this retrospective case-control study a group ofulcer patients was compared to a group ofcon trol patients not known to have peptic ulcer, but who were similar to the ulcer patients with respect to age, sex and socio-economic status. The ulcer patients were classified according to the site ofthe ulcer: gastric or duodenal. Aspirin use was ascertained for all subjects.  (Table 9.7 Dobson).
glm_multi_08.csv       |  The data are numbers of insurance policies, n, and numbers of claims, y, for cars in various insurance categories, CAR, tabulated by age of policy holder, AGE, and district where the policy holder lived (DIST = 1, for London and other major cities and DIST = 0, otherwise). The table is derived from the CLAIMS data set in Aitkin et al. (1989) obtained from a paper by Baxter, Coutts and Ross (1980).  (Table 9.13 Dobson).
glm_multi_09.csv       |En la tabla se muestran una parte de los resultados de un estudio en los Estados Unidos con el que se pretendía investigar el grado de asociación entre las aspiraciones de los estudiantes de bachillerato por proseguir con estudios universitarios y su entorno social, medido en términos del estatus socio-económico de su familia y el hecho de que recibieran apoyo en su familia para continuar estudiando (Fienberg, 1978, pag. 101).
glm_multi_10.csv       |En la tabla aparecen los datos de un estudio sobre distintos usos contraceptivos en diferentes grupos generacionales.
glm_multi_11.csv       |Los datos que se presentan (Agresti, 1990, pag 262) corresponden a un estudio en el que se pretendía concluir sobre la relación entre el grado de satisfacción en el trabajo y los ingresos percibidos.
glm_multi_12.csv       |Knowledge about the health status of trees in a forest and its influencing factors is important from an ecological and economical point of view. The data come from a specific project in the forest of Rothenbuch (Spessart), which has been carried out by Axel G¨ottlein (Technical University, Munich) since 1982. Every year, the condition of beech trees is categorized by the response variable “defoliation” (defol) into nine ordinal categories 0%, 12.5%, 25%, 37.5%, 50%, 62.5%, 75%, 87.5%, and 100%. Whereas the category 0% signifies that the beech tree is healthy, the category 100% implies that the tree is dead. In addition to the (ordinal) response variable, explanatory variables are collected every year as well. age=average age of trees at the observation plot in years; canopyd=canopy density in percent; gradient=gradient of slope in percent; alt=altitude above see level in meter; depth=soil depth in cm; ph=pH value in 0-2 cm depth; watermoistyre=level of soil moisture in three categories; alkali=fraction of alkali ions in soil in four categories; humus=thickness of humus layer in five categories; type=type of forest; fert=fertilization (Example 1.4 Fahrmeir).

# Ejecución para la lectura de cada fichero

```{r glm_poisson, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(forcats)

##### Lectura de cada ejemplo

# Datos en formato de tabla de contingencia
########################################################

# Se pasa la tabla de frecuencias a tabla de datos para procesar los diferentes modelos

# glm_multi_09
glm_multi_09=read_csv("https://goo.gl/9beSxV", col_types = "ccii")
str(glm_multi_09)
# Construimos la tabla donde cada fila recoje la frecuenia observada para combinación de las variables
glm_multi_09b = glm_multi_09 %>% gather(`AU_Si`,`AU_No`, key = "AU", value = frecuencia)

# glm_multi_10
glm_multi_10=read_csv("https://goo.gl/IcK96Y", col_types = "ciii")
str(glm_multi_10)
# Construimos la tabla donde cada fila recoje la frecuenia observada para combinación de las variables
glm_multi_10b = glm_multi_10 %>% gather(`Esterilizar`,`Otros`, `Ninguno`, key = "Metodo", value = frecuencia)

# glm_multi_11
glm_multi_11=read_csv("https://goo.gl/5T0nh0", col_types = "ciiii")
str(glm_multi_11)
# Construimos la tabla donde cada fila recoje la frecuenia observada para combinación de las variables
glm_multi_11b = glm_multi_11 %>% gather(`Muy insatisfecho`,`Poco insatisfecho`,`Moderadamente satisfecho`,`Muy satisfecho`,key = "Estado", value = frecuencia)


# Datos donde se identifica la frecuencia de cada combinación de variables
##################################################################################################

# glm_multi_01
glm_multi_01=read_csv("https://goo.gl/xx6gp2", col_types = "ccci")
str(glm_multi_01)

# glm_multi_02
glm_multi_02=read_csv("https://goo.gl/HEZtVU", col_types = "ccci")
str(glm_multi_02)

# glm_multi_03
glm_multi_03=read_csv("https://goo.gl/If7Il0", col_types = "ccci")
str(glm_multi_03)

# glm_multi_04
glm_multi_04=read_csv("https://goo.gl/8aeoB7", col_types = "ccii")
str(glm_multi_04)

# glm_multi_05
glm_multi_05=read_csv("https://goo.gl/yeCXsv", col_types = "cci")
str(glm_multi_05)

# glm_multi_06
glm_multi_06=read_csv("https://goo.gl/jPcz7x", col_types = "cci")
str(glm_multi_06)

# glm_multi_07
glm_multi_07=read_csv("https://goo.gl/z26KvC", col_types = "ccci")
str(glm_multi_07)

# glm_multi_08
glm_multi_08=read_csv("https://goo.gl/ygFQLW", col_types = "cccii")
str(glm_multi_08)
## recodificar factores
# Recodificación del factor
glm_multi_08=glm_multi_08 %>% mutate(district=fct_recode(district,"London"="1","Otherwise"="0"))

# glm_multi_12
glm_multi_12=read_csv("https://goo.gl/t1ycTq", col_types = "iicddddddddccccc")
str(gglm_multi_12)
## recodificar factores
# Recodificación del factor
glm_multi_12=glm_multi_12 %>% mutate(watermoisture=fct_recode(watermoisture,"moderately dry"="1","moderately moist"="2","moist or temporarily wet"="3"),alkali=fct_recode(alkali,"very low"="1","low"="2","moderate"="3","high"="4"),humus=fct_recode(humus,"0 cm"="0","1 cm"="1","2 cm"="2","3 cm"="3","more than 3 cm"="4"),type=fct_recode(type,"deciduous forest"="0","mixed forest"="1"),fert=fct_recode(fert,"not fertilizied"="0","fertilizied"="1"))
```
