# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
ancov_01.csv       |   The data are the birthweights (in grams) and estimated gestational ages (in weeks) of12 male and female babies born in a certain hospital. The mean ages are almost the same for both sexes.  (Table 2.3 Dobson).
ancov_02.csv       |   Frequencies of various malformations of the central nervous system recorded on live births in South Wales, UK. Study was designed to determine the effect of water hardness on the incidence of such malformations. Variables in dataset: NoCNS = count of births with no CNS problem; An = count of Anencephalus births; Sp = count of Spina Bifida births; Other = count of other CNS births; Water = water hardeness; Work = a factor with levels Manual NonManual being the type of work done by the parents.
ancov_03.csv       |   16 insulin-dependent diabetic children were enrolled in a study involving a new treatment. 8 children received the new treatment(N) while the other 8 received the standard treatment(S). The age and sex of the child was recorded along with the measured value of gycosolated hemoglobin both before and after treatment.
ancov_04.csv       |  Se ha realizado un estudio para establecer la calidad de los vinos de la variedad Pino Noir en función de un conjunto de caractersticas analizadas, por un conjunto de expertos, sobre cada uno de ellos y la región de procedencia. 
ancov_05.csv       | Tabla show data from the sales price of pre-owned VWGolf automobiles. Our goal is to model the relationship between the sales price in 1,000 Euro (variable price) and the five explanatory variables “age of the car in months” (age), “kilometer reading in 1,000 km” (kilometer), “number of months until the next appointment with the Technical Inspection Agency” (TIA), “ABS brake yes/no” (extras1), and “sunroof yes/no” (extras2).  Other varaibles are not relevant (Example 3.19 Farhmeir) 
ancov_06.csv       | The World Health Organization (WHO) has decided to conduct representative household surveys (demographic and health surveys) in developing countries on a regular basis. Among others, these surveys consist of information regarding malnutrition, mortality, and health risks for children. The American institute Macro International collects data from over 50 countries. This data is freely available at www.measuredhs.com for research purposes. In this book, we look at an exemplary profile of a data set for Zambia taken in the year 1992 (4,421 observations in total). The Republic of Zambia is located in the south of Africa and is one of the poorest and most underdeveloped countries of the world. Among several possible anthropometric indicators, we use a measure for chronic malnutrition, which is based on body height as indication for the long-term development of the nutritional condition. List of variables: zscore= Child’s Z-score; cgender = Gender; cbreastf = Duration of breast-feeding in months; cage = Child’s age in months; magebirth= Mother’s age at birth in years; mheight= Mother’s height in centimeter; mbmi= Mother’s body mass index; meducation =Mother’s level of education; mwork= Mother’s work status; region =Region of residence in Zambia; district =District of residence in Zambia (55 districts) (Example 1.2 Farhmeir) 

# Ejecución para la lectura de cada fichero

```{r ancova, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(forcats)

##### Lectura de cada ejemplo

# ancov_01
ancov_01=read_csv("https://goo.gl/B3yoLJ", col_types = "ddc")
str(ancov_01)
# Recodificación del factor
ancov_01=ancov_01 %>% mutate(sex=fct_recode(sex,"Boy"="1","Girl"="2"))

# ancov_02
ancov_02=read_csv("https://goo.gl/bNOSxt", col_types = "cdddddc")
str(ancov_02)
# Total de enfermos
ancov_02=ancov_02 %>% mutate(CNS=An+Sp+Other)

# ancov_03
ancov_03=read_csv("https://goo.gl/0iFS9L", col_types = "dccdd")
str(ancov_03)

# ancov_04
ancov_04=read_csv("https://goo.gl/OX9wgM", col_types = "ddddddc")
str(ancov_04)

# ancov_05
ancov_05=read_csv("https://goo.gl/CLtVZq", col_types = "ddddccdddddd")
str(ancov_05)
# Recodificación del factor
ancov_05 = ancov_05 %>% mutate(extras1=fct_recode(extras1,"ABS yes"="1","ABS no"="2"),extras2=fct_recode(extras2,"sunroof yes"="1","sunroof no"="2"))

# ancov_06
ancov_06=read_csv("https://hec.su/goJp", col_types = "dcdddddccccc")
str(ancov_06)
# Recodificación del factor
ancov_06 = ancov_06 %>% mutate(cgender=fct_recode(cgender,"male"="1","female"="0"),meducation=fct_recode(meducation,"no education"="1","primary school"="2","secondary school"="3","higher education"="4"),mwork=fct_recode(mwork,"mother working"="1","mother not working"="0"),region=fct_recode(region,"Central"="1","Copperbelt"="2","Eastern"="3","Luapula"="4","Lusaka"="5","Northern"="6","North western"="7","Southern"="8","Western"="9"))
```

