# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
glm_bin_01.csv       |   Table shows numbers of beetles dead after five hours exposure to gaseous carbon disulphide at various concentrations (Table 7.2 Dobson).
glm_bin_02.csv       |   Numbers of embryogenic anthers ofthe plant species Datura innoxia Mill. obtained when numbers njk ofan thers were prepared under several different conditions. There is one qualitative factor with two levels, a treatment consisting ofstorage at 3◦C for 48 hours or a control storage condition, and one continuous explanatory variable represented by three values of centrifuging force (Table 7.5 Dobson).
glm_bin_03.csv       |   A sample of elderly people was given a psychiatric examination to determine whether symptoms ofsenilit y were present. Other measurements taken at the same time included the score on a subset ofthe Wechsler Adult Intelligent Scale (WAIS). (Table 7.8 Dobson).
kyphosis       |En esta tabla aparecen los datos de 81 niños que fueron intervenidos quirúrgicamente para corregirles problemas en la columna vertebral. La variable Kiphosis indica la presencia o ausencia de una deformidad postoperatoria en la columna. LAs otras tres variables son la edad del niño en mese, número de vértebras intervenidas, y la primera vértebra involucrada en la intervención.

# Ejecución para la lectura de cada fichero



```{r glm_poisson, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(forcats)
##### Lectura de cada ejemplo

# Datos en formato de tabla de conteos (total, éxitos)

# glm_bin_01
glm_bin_01=read_csv("https://goo.gl/E2MlSZ", col_types = "dii")
str(glm_bin_01)

# glm_bin_02
glm_bin_02=read_csv("https://goo.gl/6P3zRr", col_types = "ddcd")
str(glm_bin_02)
# Recodificación del factor
glm_bin_02 %>% mutate(storage=fct_recode(storage,"Control" = "1","treatment" = "2"))


# Datos donde una variable indica el estado de la respuesta
# Cuando sea necesario se debe recodificar para que el 1 identifique el "éxito" y 0 el "fracaso"

# glm_bin_03
# éxito = tener síntomas que viene codificado con 1
# fracaso = no tener síntomas que viene codificado con 0
glm_bin_03=read_csv("https://goo.gl/6E8fhd", col_types = "dc")
str(glm_bin_03)
# Convertimos la respuesta en variable numérica para el ajuste de modelos
glm_bin_03=glm_bin_03 %>% mutate(senility = 1*(senility==1))
str(glm_bin_03)

# base de datos en libreria de R 

#kyphosis
require(rpart)
attach(kyphosis)

```

# Bibliografía

>Dobson (2002). An introduction to generalized linear models
