# Descripción de ficheros

Nombre             | Descripción
-------------------|------------------------------------------------------------
aov_01.csv       |   Genetically similar seeds are randomly assigned to be raised in either a nutritionally enriched environment (treatment group) or standard conditions (control group) using a completely randomized experimental design. After a predetermined time all plants are harvested, dried and weighed. The results, expressed in grams, for 20 plants in each group are shown.  (Table 2.7 Dobson).
aov_02.csv       |  The weights, in kilograms, of twenty men before and after participation in a ‘waist loss’ program are shown.  (Table 2.8 Dobson).
aov_03.csv       |  Table shows plasma inorganic phosphate levels (mg/dl) one hour after a standard glucose tolerance test for obese subjects, with or without hyperinsulinemia, and controls  (Table 6.18 Dobson).
aov_04.csv       |  The weights (in grams) of machine components ofa standard size made by four different workers on two different days  (Table 6.19 Dobson).

# Ejecución para la lectura de cada fichero

```{r anova, eval=FALSE}
### Para cargar los datos
library(tidyverse)
library(forcats)

##### Lectura de cada ejemplo

# aov_01
aov_01=read_csv("https://goo.gl/n1olNN", col_types = "dd")
# Para construir modelos trasformamos los datos originales en la forma habitual  
aov_01b=aov_01 %>% gather(`treatment`,`control`,key = "Group", value = "Dried")

# aov_02
aov_02=read_csv("https://goo.gl/jWGurk", col_types = "idd")
# Para construir modelos trasformamos los datos originales en la forma habitual  
aov_02b=aov_02 %>% gather(`before`,`after`,key = "Time", value = "Weight")

# aov_03
aov_03=read_csv("https://goo.gl/3L4EtK", col_types = "cd")

# aov_04
aov_04=read_csv("https://goo.gl/fXWdO3", col_types = "ccd")
```

# Bibliografía

>Dobson (2002). An introduction to generalized linear models
